# Site settings
title: PerfectlyNormalBlag
subtitle: Tales of Absolutely No Interest
name: Per Christian B. Viken
email: perchr@northblue.org
description: > # this means to ignore newlines until "baseurl:"
  Some occasional ramblings from a software developer and part-time farmer
  living in Sweden.
baseurl: "/blag" # the subpath of your site, e.g. /blog/
url: "https://eastblue.org" # the base hostname & protocol for your site
image_url: "/blag/images"
github_username:  PerfectlyNormal
permalink: /:year/:title.html

collections:
  weeknotes:
    permalink: /:year/W:week/:title.html
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock